site_name: FileSilo Documentation
site_url: https://www.notesx.net
nav:
  - Introduction: index.md
  - Setup: setup.md
  - Using: using.md
theme:
  name: material
  language: en
  collapse_by_default: true
  highlightjs: true
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - toc:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zeromancer1972
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@OliverBusse
extra_css:
  - style.css
copyright: Copyright &copy; Oliver Busse / NotesX.net
plugins:
  - search
